### ISSUE TITLE
A cornucopia of small file checking issues 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1417] opened 2020-02-08 12:29 UTC
Another set of file checking api issues / requests I’ve picked up while testing the most recent API changes.

## 1

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://sandbox.zenodo.org/record/489515/files/405-1168-1-PB.pdf?download=1&verbose=true&doi=10.1063/1.4937158`

In this response, we return a match on the author and presume it’s the same paper. I can’t see what in the author list is matching, and it shouldn’t, as this is an entirely different paper.

- [x] done

## 2

We’re missing several identifiers in docs where they’re pretty clear. I think it might be due to case sensitivity. If it is, that’s okay, I’ll just put in various versions for each line we have, unless you think we should just always ignore case when matching, I’m slightly on the fence. 

#### 2.1

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://static.cottagelabs.com/obstm.pdf`

`https://dev.openaccessbutton.org/static/test-manuscripts/voutchkova2017_iodine_in_dk.pdf`

We’re missing many of the regexes on this one. E.g we should catch all the `Received: / Accepted: / Published: `  dates.

- [x] done

#### 2.2

``https://dev.openaccessbutton.org/static/test-manuscripts/Khoo-etal-2020-NestingMaterialEnrichment.pdf`

Here we miss `Author Accepted Manuscript`

- [x] done

#### 2.3

https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/voutchkova2017_iodine_in_dk.pdf&verbose=true&doi=10.1007/s12665-017-6775-6&title=Iodine%20in%20major%20Danish%20aquifers

Here we miss “original article”

- [x] done

## 3

I think many regexes would be more robust if they only ran on the first few pages of a document. We’re occasionally getting false positives just because the strings are nice and specific in the first few pages but in the whole doc are not.

They might also work just by having them search the first few hundred words.

E.g

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://zenodo.org//record/3562947/files/paper_to_be_shared.pdf&verbose=true&doi=10.1016/j.conbuildmat.2015.12.145`

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Effectiveness_JK.pdf&verbose=true&title=Effectiveness%20of%20mineral%20waste%20management`

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://zenodo.org//record/3350880/files/Collaborative_Third_sp_28.11.14.docx&verbose=true&doi=10.1080/17425964.2015.1013026&title=Using%20Self-study%20to%20develop%20a%20third%20space%20for%20collaborative%20supervision%20of%20master%E2%80%98s%20projects%20in%20teacher%20education%20`

- [x] done

## 4

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Ethics_and_Ethos.docx&verbose=true&title=ETHICS%20VERSUS%20ETHOS%20IN%20US%20AND%20UK%20MEGABANKING%20`

This docx is being flagged as a publisher pdf, and shouldn’t be.

- [x] done

## 5

Question: are we already (in the code) actively assuming that lack of pub pdf signals mean postprint? There are some unknowns coming up in the response which I wouldn’t expect if we were, but if we’re not that’s fine too for now. 

- [x] done

## 6

`https://dev.openaccessbutton.org/static/test-manuscripts/McGibbon_et_al_-_JAMDA_2019_-_An_Analysis_of_Falls_and_Those_who_Fall_in_a_Chronic_Care_Facility..pdf`

Here we miss the crossmark logo / link in the doc which we have a regex for. It would be *great* if we could catch that as it’s usually on pub pdf files and always linked. 

- [x] done 

## 7 

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Cyberpeacekeeping-Prevent-and-Manage-Cyberattacks_Dorn-Webb_IJCWT_2019.pdf&verbose=true&doi=10.4018/IJCWT.2019010102&title=Cyberpeacekeeping%3A%20New%20Ways%20to%20Prevent%20and%20Manage%20Cyberattacks`

This has inspired me to suggest have a regex for ©.<<Publisher>. Can you make sure publisher autofills from crossref publisher keys. When it does, the above file should get spotted.

- [x] done

## 8 

Seems like many files take a long time to load or hit a bad gateway:

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://zenodo.org/record/3374058/files/AMAB-D-18-02760_R1.pdf&verbose=true&doi=10.1007/s00253-018-09611-z`

That one has done it several times for me. I think this may be a zenodo thing, but if it isn’t we should investigate. Regardless, it was taking down the dev api repeately for me. Other files that do it can be found from line 118 down [here](https://docs.google.com/spreadsheets/d/15roBCasoxe_DXtty2iN-QZU6uz4urqn5hTDjNVIe8_c/edit#gid=0).

- [x] done

**Comment by markmacgillivray** [comment] 2020-02-11 09:18
3. Assuming you mean that you don't want those 3 examples to match, it is now the case that the first and third don't but the second still does. I had already set the checker to only check the beginning of the doc but the setting was far too high, it is now set at 15000 characters which I estimate to be about 5 pages. I can reduce it if you want, but note then that longer documents that may have contents lists or glossaries etc might not reach the main content. Just let me know though, can set it to any number you want.

5. No we don't assume lack of pub pdf indicators means postprint. If there are no pub pdf indicators the value of the indication is zero. If we do find any postprint indicators it would become less than zero. If it remains at zero and the format is not pdf then we will assume it is postprint, but otherwise it stays as unknown.

6. The crossmark link does not appear in our text extraction of the PDF at all. Further investigation would be needed as to why, and perhaps an alternative way of extracting content from the PDF. A new issue would be needed to investigate this further.

7. I imagine this would already work, but you have not closed out your publisher indicator with two angle brackets, you only have one. So it is being treated as a literal string, not something to substitute. You could edit that and wait a while then see if it works. I could do this myself, but telling you is more useful because then you can check other ones and future ones, to ensure they open with two angle brackets and close with two angle brackets.

**Comment by markmacgillivray** [comment] 2020-02-11 09:21
@JosephMcArthur I had closed off all of these in the process of investigating the main problem, so I have ticked them and given you some info in the previous comment. Regarding the main problem of 100% CPU, I can now reliably cause the error to happen, which is good progress, but still investigating how to make it stop happening. Hopefully I will get it sorted this morning, leaving only the zenodo things to sort in the afternoon before live push. If I am still stuck by lunch time I will let you know, in case we want to reconsider plans.

**Comment by markmacgillivray** [comment] 2020-02-11 09:22
Note: the zenodo docs one above does not cause the problem, but still also to look at why we don't appear to successfully get content out of that. If that gets fixed as part of this process, no problem. If it doesn't, and we run out of time before live release, we should make a new issue to come back to that problem later.

**Comment by markmacgillivray** [comment] 2020-02-11 09:30
@JosephMcArthur sorry my above comments got formatted wrong by github, numbering now makes sense.

**Comment by JosephMcArthur** [comment] 2020-02-11 09:40
> 3: Assuming you mean that you don't want those 3 examples to match, it is now the case that the first and third don't but the second still does. I had already set the checker to only check the beginning of the doc but the setting was far too high, it is now set at 15000 characters which I estimate to be about 5 pages. I can reduce it if you want, but note then that longer documents that may have contents lists or glossaries etc might not reach the main content. Just let me know though, can set it to any number you want.

I'd say let's do the first three pages. I've never seen than that needed I don't think.

> 5: No we don't assume lack of pub pdf indicators means postprint. If there are no pub pdf indicators the value of the indication is zero. If we do find any postprint indicators it would become less than zero. If it remains at zero and the format is not pdf then we will assume it is postprint, but otherwise it stays as unknown.

Okay great. I thought this was the case. So, is it now possible for us, if the version status is unknown (and where file.archivable is unknown, to kick people into a 'review' deposit and show them the 'we'll double check' screen. I may later say we just make all these unknowns postprints, but for now I want to do more testing. 

> 6: The crossmark link does not appear in our text extraction of the PDF at all. Further investigation would be needed as to why, and perhaps an alternative way of extracting content from the PDF. A new issue would be needed to investigate this further.

Done in #1423

> 7: I imagine this would already work, but you have not closed out your publisher indicator with two angle brackets, you only have one. So it is being treated as a literal string, not something to substitute. You could edit that and wait a while then see if it works. I could do this myself, but telling you is more useful because then you can check other ones and future ones, to ensure they open with two angle brackets and close with two angle brackets.

Whoops, just a typo on my end. Fixed, and will look for in testing.

**Comment by JosephMcArthur** [comment] 2020-02-11 09:42
& roger that with the CPU issue. Good news that we can replicate at least. If we can't fix, perhaps you can assess the likely hood of it occurring on live, and we can make an educated guess about the risk.

**Comment by markmacgillivray** [comment] 2020-02-11 09:55
About 5, if we don't know the file type then we can't submit it to zenodo anyway. So, unless there is anything indicating it is a redeposit or a forward or a dark deposit, it would already become a review case, as far as I can tell.

**Comment by markmacgillivray** [comment] 2020-02-11 09:58
And as far as I can tell, a review means the user would see the something looks wrong page, then can confirm or not. If they confirm it says the double check page, and the deposit will come round again as a confirmed one, but only confirmed by the depositor rather than an admin, which we have now set to not automatically deposit, so we would end up getting the deposit note about that one, saying that the depositor has confirmed.

**Comment by markmacgillivray** [comment] 2020-02-11 10:52
I've reduced content to 9000 chars, roughly 3 pages.

**Comment by markmacgillivray** [comment] 2020-02-11 11:00
Fixed! It was down to what we do with extracted content in certain cases, where if it gets passed to the default OAB scrape procedure our attempts to regex match on certain email patterns was too hard for the length of content provided in the full doc (this was separate from the restricted lengths on the permissions checks itself). So I have added a length restriction to the main OAB scrape as well, also of 3 pages, since if we think that is where the useful content usually is, no point checking bigger docs.

It is not clear why this did not definitely happen all the time with large content, and it was certainly tested with large content, but those zenodo files did have some non-standard artefacts in them that may have been causing problems for the regex searches. Because the regexes were not actually failing, and were not technically in an infinite loop, they seemed to just recurse into the document content for a very long time, using all the CPU and stopping the API being able to respond to anything else, without actually crashing it.

I think that is all the issues here fixed, so you can close this issue unless there is anything else you want done @JosephMcArthur

**Comment by JosephMcArthur** [comment] 2020-02-11 11:29
> I've reduced content to 9000 chars, roughly 3 pages.

I've just thought. 9000 chars being roughly three pages presumes those pages are full of text, right? Given that the first part of docs are usually more spacious, and have less text per page, due to big titles and what now I wonder if we should lower again. Maybe 6000 would be even safer. Just saw the verbose response still pulling out a lot of text in ones from 3 (where we now get 2/3 right) which inspired this line of thinking.

**Comment by markmacgillivray** [comment] 2020-02-11 15:41
Reduced to 6000

**Closed** 2020-02-11 15:44 UTC
Labels: 1. Shareyourpaper.org, 2. Enhancement
