### ISSUE TITLE
[bug] request listed in the UI but leads to 404

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#783] opened 2017-07-13 15:02 UTC
https://openaccessbutton.org/request/Wnewjn77gyiZihfES

**Comment by JosephMcArthur** [comment] 2017-07-17 13:09
should be fixed now, right @markmacgillivray ? Caused by lack of profile, which now have a check for.

**Comment by markmacgillivray** [comment] 2017-07-17 13:18
Nope, different thing fixed, still to look at this one.

**Comment by markmacgillivray** [comment] 2017-07-23 18:26
Fixed - an error arose from the old nginx config and the use of a "new" page for requests which we don't use any more. Removed the old page file and changed the nginx config.

**Closed by markmacgillivray** 2017-07-23 18:26 UTC
Labels: bug
