### ISSUE TITLE
It’s possible to end up on the results page without a title being shown

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1332] opened 2019-12-08 18:49 UTC
To replicate:

- Go to https://ulib.iupui.edu/services/ILLTest 
- Input : doi.org/10.1177/0018726700538001
- You’ll see the result appears with no title

When we find that little info, we should just go straight to the wrong article page, as we'll 100% need more info. 

So, that it's possible here is one problem, but I'm also unclear why we don't get any info for this doi. Crossref appears to have it: https://api.crossref.org/v1/works/10.1177/0018726700538001.

**Comment by JosephMcArthur** [comment] 2019-12-08 18:59
okay, I realized why doi.org/10.1177/0018726700538001 didn't work. 

Using 10.1177/0018726700538001 was fine, but we didn't log doi.org/10.1177/0018726700538001 as a doi. We should.

**Comment by markmacgillivray** [comment] 2019-12-17 07:40
So it turns out this was not a bug, but down to how people may provide DOIs. We did already strip doi: but not doi.org/ unless it was provided as part of a fuller URL, so the code to find a DOI within a url / search parameter have been improved to find this sort of DOI (on dev).

**Comment by markmacgillivray** [comment] 2019-12-17 08:02
Still looking at why we might be showing that page without going straight to getting more info though - that is a separate thing, probably also not a bug but a gap in the logic that we built in the first place. So not closing this one yet as still looking at that.

**Comment by markmacgillivray** [comment] 2019-12-17 23:02
There was a logic error in the case where the backend does return a response that has some ill info but does not have a title leading us to show that page incorrectly. It has been fixed on dev now so that it does go straight to the search page if none of the required metadata is found on first check, regardless of what other info is available.

**Closed by markmacgillivray** 2019-12-17 23:02 UTC
Labels: 1. InstantILL, 2. bug
