### ISSUE TITLE
woe is me file checking system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1377] opened 2020-01-14 15:18 UTC
cc @natalianorori 

Doing some file checking testing, and will leave comments and issues as seen.

- [x] Have seen that the file checking API is cleaner and now returns the version name it thinks it is clearly. This is fab. Can we extend this clarity to if we think this is in fact the paper it says it is?
- [x] How hard would it be to 'merge' in some metadata (when we have it) into [our spreadsheet](https://docs.google.com/spreadsheets/d/1XA29lqVPCJ2FQ6siLywahxBTLFaDCZKaN5qUeoTuApg/edit#gid=0). There are a couple of things, like DOIs & ISSNs that it would be helpful to be able to merge into statements.
- [x] It would appear that links like this:

`https://dev.openaccessbutton.org/static/test-manuscripts/Lobel_Coase_and_the_Platform_jan_2019.docx`

do not work in the system. 

That link downloads the file, and I think it throws the API off. If this a testing artifact, then that's fine for now, however, right now it means it returns saying it doesn't know the file type (and it should be an AAM).

- [x] There are a couple of occasions where the API is turning saying this is <500 words where it isn't:

* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Unwelcome_Change-_Coming_to_Terms_with_Democratic_Backsliding_Lust.pdf&doi=10.1146/annurev-polisci-050517- 114628`
* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Copy_Dixon_article_as_pdf (2).pdf`
* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/weitz_hair_and_power_article.pdf`

- [x] On some files, there is a statement saying 'Rick says any version of article can be posted now' when it looks like actually it's saying postprint.

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/dinh_zarr._sleet_sb_article_1-s2.0-S0749379701003786-main.pdf&title=Reviews%20of%20Evidence%20Regarding%20Interventions%20to%20Increase%20the%20Use%20of%20Safety%20Belts`

- [x] There are a few occasions we're missing strings it seems like we should find:

* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/A_green_tea___triggered_genetic_control_system_for_treating_diabetes_in_mice_and_monkeys.pdf&doi=10.1126/scitranslmed.aav8826&title=A%20green%20tea%E2%80%93triggered%20genetic%20control%20system%20for%20treating%20diabetes%20in%20mice%20and%20monkeys` & `https://dev.openaccessbutton.org/static/test-manuscripts/A_green_tea___triggered_genetic_control_system_for_treating_diabetes_in_mice_and_monkeys.pdf` we should find 'downloaded at' on the RHS
* `https://dev.openaccessbutton.org/static/test-manuscripts/dinh_zarr._sleet_sb_article_1-s2.0-S0749379701003786-main.pdf` we should find 'published by`
* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/voutchkova2017_iodine_in_dk.pdf&doi=10.1007/s12665-017-6775-6&title=Iodine%20in%20major%20Danish%20aquifers` we should find `original article`, `accepted`, the crossmark url and a few other bits.
* `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Burrow_and_Rainone__2016_.pdf&doi=10.1016/j.jesp.2016.09.005&title=How%20many%20likes%20did%20I%20get?:%20Purpose%20moderates%20links%20between%20positive%20social%20media%20feedback%20and%20self-esteem.` here we miss `all rights reserved` and `Revised` / `accepted` etc. 

- [x] Would appreciate your advice on file names like this:

> dinh_zarr._sleet_sb_article_1-s2.0-S0749379701003786-main.pdf

This is a dead giveaway that it's download from science direct (am I right @natalianorori?). There is an ID:

> PII S0749-3797(01)00378-6

in the file that matches too (with special characters removed).

Any thoughts on catching these? 

- [x] I think it would still be good to show (even externally) the checks we did. This would be good for testing too.

- [x] I think we will want to catch the (C) symbol a fair bit. If you could think about a best way to do this as discussed that would be great.

- [x] Mark, we're focusing a lot on what humans can see. Is there any file meta-data or things that are easily visible to a computer but not easy to us? Thinking about something like what you get when you hit 'get info' on a file in finder on macs. For example, for one file I can see `Where from:` it was downloaded, and if this was sciencedirect that would be a dead giveaway. Similarly, if I make a file locally, that field isn't present at all (to my eyes), suggested I made it locally, and then it's an AAM.

**Comment by markmacgillivray** [comment] 2020-01-14 20:41
By the way you can still get back the full response from the permissions endpoint by adding verbose=true to the params. I am just reading through the points in this issue now as I am already working on some of these, so will tick things off as I go.

**Comment by JosephMcArthur** [comment] 2020-01-14 20:44
Thank you! Perfecto.

**Comment by markmacgillivray** [comment] 2020-01-14 21:06
File now returns a match true/false to let us know if we think it is the file it says it is.

**Comment by JosephMcArthur** [comment] 2020-01-14 21:10
💯

**Comment by markmacgillivray** [comment] 2020-01-14 21:14
For adding metadata into the statement strings, I have added code that will find where you have done something like what you did in one of the examples in the sheet, where you have <<DOI>>. In that case it will replace <<DOI>> with the DOI if we have it.

This will work for any metadata item that we are able to find, so you can use <<ISSN>> as well for example.

NOTE this will only work for one replacement within the string, and only one time, so don't write string matches that contain <<DOI>> more than once, or that contain multiples such as <<DOI>> and <<ISSN>>. This seems unlikely to be necessary anyway, as a string with just one of those values that matches would be sufficiently complex and accurate.

**Comment by JosephMcArthur** [comment] 2020-01-14 21:28
Github also uses << arrows to mean stuff. 

`<<DOI>>`

is the right format for a merge, yes?

Right now, we only need DOI and ISSN.

**Comment by markmacgillivray** [comment] 2020-01-14 21:30
Oh yeah sorry, forgot that. Yes, what you typed is right.

**Comment by markmacgillivray** [comment] 2020-01-14 22:35
Downloading docx does work, just had to update the test stuff to handle it, tested and works now.

**Comment by JosephMcArthur** [comment] 2020-01-14 22:36
\o/ you rock! Great to be ticking these off. Means we can do the next round of testing ASAP and learn more things to improve :D

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment] 2020-01-14 22:42
About "Rick says any version of article can be posted now" perhaps we have a miscommunication - I thought you'd previously said that if Rick can_post_now is true then we can definitely deposit the item. Is that not the case?

I have seen some that are true and some that are false (e.g. where there is an embargo), but in either of those cases we CAN post as long as we have the right version and deposit with the necessary embargo data. So if can_post_now does not definitely mean we CAN post now no matter what, then it is not clear that it serves any useful function.

If I misunderstood, and can_post_now: true should NOT indicate we can accept anything, that is easy to fix - I will just take that first step out of the logic, and ignore the can_post_now value altogether and proceed to checking WHAT can be posted. Just let me know.

**Comment by markmacgillivray** [comment] 2020-01-14 23:28
Looking at the example you gave above about can_post_now, it appears that Ricks uses can_post_now to indicate that the specified item can be posted now if it is outside the embargo period. So, in the example you gave, can_post_now is only true because the embargo period ended many years ago.

So it seems can_post_now should NOT indicate that any version can be posted. Probably I misunderstood that.

However, this then implies that if can_post_now is false, and we are still in the embargo date, then we CAN'T post the specified item, even if we do follow the can_post_now conditions. So, for the case of an item where we apparently can post the postprint, but we are still within the embargo period, the can_post_now value would be false, and that would appear to mean that we can't even post the postprint either.

So what does "post" mean in the context of "can_post_now"?

If we are in the embargo period for the given document type, and we have that document type, the can_post_now value will be false, so should we not put that item in zenodo with the relevant embargo information? Or do we just put it into zenodo anyway, making the can_post_now value irrelevant to us? That seems to be the only logical solution.

**Comment by markmacgillivray** [comment] 2020-01-14 23:52
For the case where you are saying the title includes a science direct identifier, wouldn't that be just another case of a regex we should add to the sheet? The sheet already has the option of searching in the file or the title, and when it is title the code already checks the file name and the metadata title if we have it. So just add a regex to the sheet that checks in title, and can match the science direct identifier/filename structure.

For example it looks like it is going to contain an S followed by a few numbers, any idea how many, is it always the same amount, or a minimum amount? And then it will end in .pdf.

So the regex would be something like the following, if we can expect the science direct identifier to appear in the file name ending with .pdf and containing at least 6 digits after an S:

S\d{6,}.*?\.pdf$

**Comment by markmacgillivray** [comment] 2020-01-15 00:11
For the docx example given above that does now download, you say it should be an AAM. What should have indicated that? I still get "unknown". Is it just that you want all non-pdf files to be marked as AAM? I have already made it so that non-pdf files are marked as acceptable, but did not specifically set their version as AAM as well, but can do if that is what you mean.\

Also, in that example, the file is still not marked as acceptable though, because without any further metadata the file cannot be matched to confirm it is what it says it is. I've done that on purpose, so that without metadata or without matching the metadata given, we won't just accept any file. But I could change that too, if you want any file that is not a pdf to just automatically be assumed to be the right thing, I could alter it to do that.

Let me know on both the above, easy to change.

**Comment by markmacgillivray** [comment] 2020-01-15 00:20
For all the cases of the strings you said we missed but should find, I have tested them all and they all now do get found. This was possibly just due to changes being made at the time or file download issues, but all now work.

I note though that on one of them you say we should find original article, url, crossmark and "a few other bits" - at the moment the string checker only looks for any string in the sheet and as soon as it finds one it stops. So it would not give you a full list of all those matches, only ever the first one it finds. I can change that as well to give you confirmation of all the ones it can find, but that will just make it slower when it could be faster.

**Comment by markmacgillivray** [comment] 2020-01-15 00:39
For the 3 PDFs where the API says they are less than 500 words:

* the first and third PDFs are causing errors in our text extraction system because of errors within the PDFs themselves. We have error catching that stops that from causing a total failure, but it still results in us getting no text out of them. Each PDF causes a different error, at different points in the PDF, due to errors in how the PDFs were initially created. I am doing some work to upgrade our PDF extraction to see if it is possible for us to get at least some text out from them before the errors occur. I'll add another comment to this issue once I make some progress with this.

* the second PDF is actually a scan, so the content of the PDF is nothing but images that happen to contain things that look like text - but there is no actual text in it. It is possible to do text extraction from images, but it would take a bit more work to add that to our system - it would need a separate issue and some scheduling, probably two or three days of work with a few different test files and working through various possibilities.

**Comment by markmacgillivray** [comment] 2020-01-15 04:02
For the 2 PDFs that cause errors, the errors are internal to the pdf parsing libraries, and actually cause them to error completely, so we can't catch them to get any of the preceding content. To get around this, for the PDFs that do cause errors, we would need to spend some time writing our own direct implementation of the underlying pdf rendering code. This will need scheduling as a new issue, and is probably a few days work, 2 days anyway.

**Comment by markmacgillivray** [comment] 2020-01-15 08:04
FYI I still have to look at the copyright symbol problem and the non-human metadata possibilities - should get to those tomorrow. Everything else is ticked or else has a question in the above comments for you to let me know about, then can be finished off.

**Comment by JosephMcArthur** [comment] 2020-01-15 08:46
Look at this on Github, as I may edit after.

## ricks

>About "Rick says any version of article can be posted now" perhaps we have a miscommunication - I thought you'd previously said that if Rick can_post_now is true then we can definitely deposit the item. Is that not the case?

> I have seen some that are true and some that are false (e.g. where there is an embargo), but in either of those cases we CAN post as long as we have the right version and deposit with the necessary embargo data. So if can_post_now does not definitely mean we CAN post now no matter what, then it is not clear that it serves any useful function.

> If I misunderstood, and can_post_now: true should NOT indicate we can accept anything, that is easy to fix - I will just take that first step out of the logic, and ignore the can_post_now value altogether and proceed to checking WHAT can be posted. Just let me know.

Let's proceed to checking what can be posted, and ignore the can_post_now true / false for now. Will bring this up with them. 

## Science not so direct

> For the case where you are saying the title includes a science direct identifier, wouldn't that be just another case of a regex we should add to the sheet? The sheet already has the option of searching in the file or the title, and when it is title the code already checks the file name and the metadata title if we have it. So just add a regex to the sheet that checks in title, and can match the science direct identifier/filename structure.
> 
> For example it looks like it is going to contain an S followed by a few numbers, any idea how many, is it always the same amount, or a minimum amount? And then it will end in .pdf.
> 
> So the regex would be something like the following, if we can expect the science direct identifier to appear in the file name ending with .pdf and containing at least 6 digits after an S:
> 
> S\d{6,}.*?.pdf$

Good point! I've changed it to

`S\d{15,}.*?.pdf$`

having read in https://en.wikipedia.org/wiki/Publisher_Item_Identifier that's what we can expect. It's in the sheet now. 

# docx

> For the docx example given above that does now download, you say it should be an AAM. What should have indicated that? I still get "unknown". Is it just that you want all non-pdf files to be marked as AAM? I have already made it so that non-pdf files are marked as acceptable, but did not specifically set their version as AAM as well, but can do if that is what you mean.

We should set the version of non-PDF files to AAM, yes*. From that version, if ricks says an AAM is allowed, it's acceptable.

Note: we are making a pretty big presumption about what we'll get here, i.e we won't get pre-prints, but I think that's fine. This is an IR, NOT an a preprint server. Pre-prints, by their very nature, should be published elsewhere and we should get links. If that changes, this rule will break, but for right now it's okay. 

>Also, in that example, the file is still not marked as acceptable though, because without any further metadata the file cannot be matched to confirm it is what it says it is. I've done that on purpose, so that without metadata or without matching the metadata given, we won't just accept any file. But I could change that too, if you want any file that is not a pdf to just automatically be assumed to be the right thing, I could alter it to do that.

No this is right. We need some meta-data to accept a file, technically it could be valuable to check a file version without meta-data, but we want to be careful to scope this api about checking stuff before deposit so that limitation makes sense. The only thing I'd add is that if we get no metadata (including from the file) then we should give an error that states that as the reason for rejection, not saying that we just can't confirm what the version is / it's not acceptable. 

> Let me know on both the above, easy to change.

## missing strings

> For all the cases of the strings you said we missed but should find, I have tested them all and they all now do get found. This was possibly just due to changes being made at the time or file download issues, but all now work.

> I note though that on one of them you say we should find original article, url, crossmark and "a few other bits" - at the moment the string checker only looks for any string in the sheet and as soon as it finds one it stops. So it would not give you a full list of all those matches, only ever the first one it finds. I can change that as well to give you confirmation of all the ones it can find, but that will just make it slower when it could be faster.

My presumption was that checking for all strings would be pretty fast vs the time needed up upload files etc. Am I wrong?

Right now, I'd say let's do the full scan, as that helps with debugging and understanding how it's performing. 

## PDF parsing

> For the 3 PDFs where the API says they are less than 500 words:

> the first and third PDFs are causing errors in our text extraction system because of errors within the PDFs themselves. We have error catching that stops that from causing a total failure, but it still results in us getting no text out of them. Each PDF causes a different error, at different points in the PDF, due to errors in how the PDFs were initially created. I am doing some work to upgrade our PDF extraction to see if it is possible for us to get at least some text out from them before the errors occur. I'll add another comment to this issue once I make some progress with this.

> the second PDF is actually a scan, so the content of the PDF is nothing but images that happen to contain things that look like text - but there is no actual text in it. It is possible to do text extraction from images, but it would take a bit more work to add that to our system - it would need a separate issue and some scheduling, probably two or three days of work with a few different test files and working through various possibilities.

> For the 2 PDFs that cause errors, the errors are internal to the pdf parsing libraries, and actually cause them to error completely, so we can't catch them to get any of the preceding content. To get around this, for the PDFs that do cause errors, we would need to spend some time writing our own direct implementation of the underlying pdf rendering code. This will need scheduling as a new issue, and is probably a few days work, 2 days anyway.

Helpful. When we get errors like this, can the API say that rather than delivering 1 as the number of words? Seems like if we get a error here whatever is catching that now can also do that, but if it's more complex no worries! 

# other

> FYI I still have to look at the copyright symbol problem and the non-human metadata possibilities - should get to those tomorrow. Everything else is ticked or else has a question in the above comments for you to let me know about, then can be finished off.

Both of these can wait, they're not issues I've seen in testing so far (although the (C) issue may be masked by matching only the first in the list). Of course... you're clearly in the zone on this atm, so if you just want to plow on go for it.

**Comment by JosephMcArthur** [comment] 2020-01-15 22:54
- [ ] In this the system is saying 'sherpa says green so any file is allowed'. If it's green, only pre and postprints are allowed. `https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/2010_Camp_governance_LB.pdf&doi=doi:10.1093/jrs/feq014&title=Governance, Governmentalities, and the State of Exception in the Palestinian Refugee Camps of Lebanon`

**Comment by markmacgillivray** [comment] 2020-01-15 22:56
When you say "if Rick says an AAM is allowed", what do you mean by that? Rick says things about preprints, postprints, and publisher PDFs. Do you mean that if Rick says postprints are allowed then AAM is allowed? Or is preprint good enough for AAM? AAM is not a publisher PDF, but I guess if publisher PDFs are allowed then AAMs are allowed too anyway, right?

**Comment by markmacgillivray** [comment] 2020-01-15 22:59
Hmm, what is the difference between green, blue, and yellow in sherpa then? I thought green and blue indicate any file, and yellow indicates anything but publisher pdf. What should each colour be instead?

**Comment by natalianorori** [comment] 2020-01-15 23:01
Hey, just jumping in to say preprint is not good enough for AAM. preprint is the submitted version, postprint is the AAM. We are always aiming for AAM. Most of the times, publisher PDFs are not allowed but AAMs are. 

A little bit on colors below: 

Green: Preprints, and postprints (AAMs) are allowed. But Publisher PDFs are not allowed. 
Yellow: Postprints (AAMs are allowed. Publisher PDFs and preprints are not allowed. 
Blue: Publisher PDFs, preprints and postpritns are allowed (this is the only color where everything is allowed)

White: Nothing is allowed. 

Grey: Nothing is allowed, but becasue we don't have any publisher info for the journal.

**Comment by markmacgillivray** [comment] 2020-01-15 23:03
OK thanks @natalianorori I will change it to match that!

**Comment by JosephMcArthur** [comment] 2020-01-15 23:04
> Hmm, what is the difference between green, blue, and yellow in sherpa then? I thought green and blue indicate any file, and yellow indicates anything but publisher pdf. What should each colour be instead?

If grey, white, or no response: nothing allowed
If green: pre-print or postprint
If blue: post-print (technically, pub pdf can be allowed but we have never actually returned that as in practice is color actually doesn't get used that way it seems)
If yellow: pre-print

**Comment by markmacgillivray** [comment] 2020-01-15 23:05
@JosephMcArthur - for changing the system to run through all string checks and not just stop when it finds one, which one of them should we use to indicate the actual version if there is a conflict? e.g. if we run through all the strings in the sheet and we find some that indicate it is a publisher pdf and others that indicate it is a postprint, which takes precedence?

**Comment by markmacgillivray** [comment] 2020-01-15 23:06
Oh dear @JosephMcArthur and @natalianorori your advices on which colours represents what appears to differ. Can you both confer and agree which I should use? Thanks.

**Comment by JosephMcArthur** [comment] 2020-01-15 23:06
> AAM is not a publisher PDF, but I guess if publisher PDFs are allowed then AAMs are allowed too anyway, right?

Nope, I wouldn't presume that. Some folks want you to share the pub pdf but explicitly not AAM. Best to just to explicitly what Rick tells you as that's what it's designed to do. Trying to get away from ambiguous answers and colors.

**Comment by JosephMcArthur** [comment] 2020-01-15 23:07
> Oh dear @JosephMcArthur and @natalianorori your advices on which colours represents what appears to differ. Can you both confer and agree which I should use? Thanks.

Natalia is technically correct (except on yellow I think), I'm just making a different judgement as I said :) Use me ;)

**Comment by markmacgillivray** [comment] 2020-01-15 23:07
@JosephMcArthur OK I won't have it assume that - but still need to know which one of the Rick types means AAM is acceptable - should I only match AAM to postprint?

**Comment by JosephMcArthur** [comment] 2020-01-15 23:08
AAM = postprint = accepted

**Comment by markmacgillivray** [comment] 2020-01-15 23:08
Ah natalia has already said that postprint is the only one that is AAM, OK.

**Comment by natalianorori** [comment] 2020-01-15 23:08
use Joe! He is right on yellow

**Comment by JosephMcArthur** [comment] 2020-01-15 23:11
Words are fun, right guys? 

Sorry for not being careful enough with mine! I skip between standards, library lingo, and author lingo without even thinking about it.

**Comment by JosephMcArthur** [comment] 2020-01-15 23:21
Just storing here.

- [ ] Need to decide who to rank different strings we may match

Options so far:

> perhaps, the pub pdf one should take precedent if we want to be conservative
> or, we could do a simple scoring system. I can put points next to each. you add up the matches. if +ve num, publisher. If -ve, AAM.  (presuming we start at zero)

> for now, take first as truth, but show matches for all so we can test

**Comment by markmacgillivray** [comment] 2020-01-16 00:45
OK changes to decision criteria as agreed in above comments have been made. PDFs that error out have a specific unacceptable reason given. String matches are all run and all matches are returned, and currently a ve score is counted but not yet used, so the file version will still be set to the first match made. This is easily changed though.

Copyright symbol matching, and checking within file metadata, are still to be looked at.

**Comment by natalianorori** [comment] 2020-01-16 23:06
Hey @markmacgillivray. I've re tested all the previous files once again. You've made great progress!  However, I've still seen an issue with docx files not being read correctly. 

Here are a few examples: 
https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Lobwel_Coase_and_the_Platform_jan_2019.docx&verbose=true 

https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Ethics_and_Ethos.docx&verbose=true

both say "Insuficient metadata to validate file" and marks them as AAM because they are not PDF. Is this what we expect it to do?

**Comment by JosephMcArthur** [comment] 2020-01-16 23:21
> https://dev.openaccessbutton.org/static/test-manuscripts/Lobwel_Coase_and_the_Platform_jan_2019.docx

This link doesn't work, which explains the response!

I've review and think about the below one in the morning. I might be complex, and sort of a good case for me to think through some of the above decisions. 

> https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Ethics_and_Ethos.docx&verbose=true

**Comment by markmacgillivray** [comment] 2020-01-17 02:43
Hi @natalianorori and @JosephMcArthur - first, yes, one of those file links just doesn't work, so that is the problem there.

For the other one, we are able to get the file. The file is marked as an AAM because it is not a PDF, and we were not able to identify it as being any other kind of file, so yes at the moment the default is AAM for any file that is not a PDF. PDFs would stay as version "unknown". I did this because Joe asked to have AAM be the default version for any file that is not a PDF, if we don't find any other version info.

But also yes, as you noted, we are unable to match enough metadata to actually be certain that the file is the article we think it is. So, even though we say it is an AAM, we are unable to confirm that the content of the file IS the thing we think it is. This is happening because here in testing we are not able to find any more metadata just based solely on the file name, so we can't confirm it. However, if you provided the article doi or title as URL params and we were able to find those within the file, then the file would be marked as acceptable. In real world usage, we are much more likely to be getting files submitted along with metadata anyway, so this is going to be less of a problem. 

However at the moment it would still be possible sometimes that we get given a file that is not a PDF so we mark it as an AAM (or something else if we find other indications within the file of it being a postprint or publisher pdf), but we still may not be able to find enough metadata within the file itself. These are separate identifications - one is, what version is this file? The other is, does this file appear to contain what we think it should?

I can change these configurations if desired, but at the moment I think I've got it right for how it was intended by Joe at least - but maybe he needs to discuss more with you to make sure he has the right idea :)

**Comment by JosephMcArthur** [comment] 2020-01-17 09:53
Interesting case here:

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Khoo-etal-2020-NestingMaterialEnrichment.pdf&verbose=true?doi=10.1177/0023677219894356&title=Nesting%20material%20enrichment%20reduces%20severity%20of%20overgrooming-related%20self-injury%20in%20individually%20housed%20rats`

In Natalia's review, she noticed we missed: `author accepted manuscript` in the file, which wasn't on our string list. I've put it on the list now, but it's not matching, likely as the system just isn't indexing the file every minute which is totally reasonable. 

- [ ] how often do we check the sheet for new strings to match?

Then, we are being told we're matching two things;

`(c) the authors`

I can't find a (C) statement in the file, but I can find `the authors`. It looks like we might be missing this. 

It also says we're finding the ISSN. I can't see it with my eyes, and control find can't find it either. 

Mark, can you look at the above cases?

**Comment by JosephMcArthur** [comment] 2020-01-17 09:57
By chance, the very next file I looked at had the same `(c) the authors` issue:

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/psychnurses_vfinal.pdf&verbose=true&title=Just%20What%20the%20Nurse%20Practitioner%20Ordered%3A%20Independent%20Prescriptive%20Authority%20and%20Population%20Mental%20Health`

One fix may be, looking only on the first one or two pages.

**Comment by JosephMcArthur** [comment] 2020-01-17 09:59
> https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Ethics_and_Ethos.docx&verbose=true

and 

> https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/Lobel_Coase_and_the_Platform_jan_2019.docx&verbose=true&title=Coase%20%26%20the%20Platform%20Economy

Now both give errors:

> TypeError: Cannot read property 'can_post_now_conditions' of undefined at Object.API.service.oab.permissions (server/service/oabutton/permissions.coffee:278:8) at Object.get [as action] (server/service/oabutton/permissions.coffee:6:28) at Route._callEndpoint (server/lib/aestivus.coffee:298:27) at server/lib/aestivus.coffee:180:33 at server/lib/aestivus.coffee:50:9

This looks like a possible issue with ricks. I have asked them to change some stuff, so I was sort of expecting it may break, but looking at their end I don't see the changes I'd expect so I don't think it's that. Not sure thought!

**Comment by JosephMcArthur** [comment] 2020-01-17 10:04
Otherwise. Mark, we've made massive strides here, most things are giving a sensible response, and I think we're tackling most of the hard bits of problems! As one would expect with many chefs there are a few loose ends here and there but we'll get around to tidying it up.

The issue about ranking, and what to do with PDFs where we find no +'ve signals for AAMs (but, also no signs of publisher pdf) I'm going to punt on for a while until we've done more testing and had more discussion. The trick for me will be getting to place where we feel like we have such good coverage of pub pdf statements that we see everything the api gives 'unknown' in this case, it's actually an AAM! I think there may also be some signals we're not yet counting as pub pdf, but that once we include decent score ranking we could include like DOIs.

**Comment by markmacgillivray** [comment] 2020-01-17 11:40
I fixed that can_post_now_conditions error just now, so that it won't block you in testing today. It's too late to look at the other points right now, but at least that lets you continue if Ricks is down. I had introduced some checks of ricks data later in the permissions algorithm and had not included a check in case the earlier call to ricks had failed, so that was causing that error. Ricks format seems the same at the moment and it is responding just now, it was probably just down for a while again earlier.

**Comment by JosephMcArthur** [comment] 2020-01-17 11:44
Thank you again! I have flagged with them the API goes down from time to time for some things. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment] 2020-01-19 21:09
I've just been reorganising issues in milestones to better reflect the order I actually ended up doing things last week and this week. This is just a note here to remind me I worked on this one mostly in milestone 76, but I am leaving it in milestone 77 because there are still a few points above for me to check, and we may get more. I have also moved some issues that should have been done in 76 into 77, because they were not done due to working on this one first, and some bug issues that came in.

I'll get back to looking at points in this issue once I have done a few of the other outstanding issues as this coming week (milestone 77) progresses.

**Comment by JosephMcArthur** [comment] 2020-01-20 09:02
- [ ] write a script to give us direct FT links to zenodo requests that are successful and have zenodo records

I think a good link looks like this https://zenodo.org/record/3613270/files/3.pdf (which automatically downloads the file)

This can be used as a positive control for the file checking system.

**Comment by JosephMcArthur** [comment] 2020-01-21 08:13
On the scoring, it seems to me that +ve scores are not being matched as publisher pdfs. for instance:

`https://dev.api.cottagelabs.com/service/oab/permissions?url=https://dev.openaccessbutton.org/static/test-manuscripts/ARER_Wu2.pdf&verbose=true?doi=doi.org/10.1146/annurev-resource-100518-094151&title=Agglomeration%3A%20Economic%20and%20Environmental%20Impacts`

Generally, I'd suggest:
+ve = publisher pdf
0 = unknown
-ve= postprint

**Comment by markmacgillivray** [comment] 2020-01-22 03:15
About non-human file metadata:

There is file metadata in a pdf, but it is not necessarily the same as what you see from "get info" on a Mac. If there is a "where from" value there, it is likely just where you get it from if you download it, not necessarily where it was created. However, the metadata that is in the PDF could have some identifying features in it, if publishers ever put any there.

It is easy enough to get the metadata from a PDF when we do the text extraction, and we could add to our sheet of strings to check, and have a new type called "metadata", then look for those strings/regexes within the metadata of the file.

But to do this we would first need to look through some PDF files and see if we can actually find any such strings.

If you want to check some PDFs, you can use this URL:

https://dev.api.cottagelabs.com/convert?metadata=true&from=pdf&to=txt&url=YOURPDFURL

**Comment by JosephMcArthur** [comment] 2020-01-22 10:45
- [ ] When on live, can we have the file checking system read from this file: https://docs.google.com/spreadsheets/d/10DNDmOG19shNnuw6cwtCpK-sBnexRCCtD4WnxJx_DPQ/edit#gid=0

We'll need to validate everything we put in here on dev first to check we dont increase false positive rate, so best to have a dev & live sheet established.

**Comment by markmacgillivray** [comment] 2020-01-22 21:37
For +ve scoring, yes, it wasn't setting based on the score yet because we hadn't yet agreed if that was what you wanted. But now that you have confirmed, I have turned that on. So, whenever we find an indicator of publisher pdf or postprint, we set the version to that. Then at the end if the ve count is positive we override to being publisher pdf, and if it is negative we override to being postprint.

If ve is 0 because we found an equal amount of indicators for each, then the version would be whatever the last match was. Is this what you want? Or if ve is 0 should we reset to unknown?

**Comment by JosephMcArthur** [comment] 2020-01-23 07:24
0 should reset to unknown for now

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment] 2020-01-24 00:49
ve 0 is set to default to unknown.

About copyright: 
If the copyright symbol is used in a pdf or doc it is most likely used as the unicode symbol ©. In this case it should be possible for that to be used in the google sheet (I have checked and it does use the standard unicode representation of it) and the regex should match it. I have turned on unicode support for the regex in question, just in case it is necessary.

I think this is the last thing left to do in this issue, please close if you are happy with it all.

**Closed** 2020-01-24 07:40 UTC
Labels: 1. Shareyourpaper.org, 2. Enhancement
