### ISSUE TITLE
Generate nicer emails for shareyourpaper.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1365] opened 2020-01-07 11:13 UTC

**Comment by JosephMcArthur** [comment] 2020-01-14 09:48
So, a few things here:

- [ ] it would be great if you could point me to the code that runs these emails, or dump templates in the email folder as usual (perhaps in a new sub-folder). That would help me get around to editing copy when I have a moment.
- [ ] can you have the json formatted like we do in InstantILL emails
- [ ] is it possible to show fields we normally get even if we don't have them? I think normally we hide them if we have nothing, but it helps folks on the otherside if the output is consistent even if the field is empty. 
- [ ] in the subject line can you include a throw away ID (not important, could be any unique id we already have, or doi, or anything really) just to stop all of these threading in inboxes so they're easier to process.
- [ ] can you include any clever additions you have, like the admin override links, in emails with enough copy for me to know what it is. Then I can edit around it.

**Comment by markmacgillivray** [comment] 2020-01-22 22:48
Note, if you want to make email templates for these, you can go ahead and do so - put them in the usual emails folder in the repo, then just update this issue with instructions of which new template you want me to use. Then I will adjust the code to look for that template instead of just dumping text as it currently does.

**Comment by markmacgillivray** [comment] 2020-01-22 22:49
For copy/pasting into spreadsheets, I guess you could dump data to a table in the email. It would need to be an html template for that, not a text template. Or else add the data as a csv attachment, but that is probably more hassle than just copying it out of the email.

**Comment by markmacgillivray** [comment] 2020-01-22 22:51
And for showing the fields we normally get even if there is no value, yes, if you listed them in an email template they would show up even if the value to go next to them (or under them if done as a table) ends up being empty.

**Comment by markmacgillivray** [comment] 2020-01-22 22:57
As far as I can see the JSON in the instantill emails is formatted in the same way. What difference is it you are wanting?

**Comment by JosephMcArthur** [comment] 2020-01-23 08:02
> Note, if you want to make email templates for these, you can go ahead and do so - put them in the usual emails folder in the repo, then just update this issue with instructions of which new template you want me to use. Then I will adjust the code to look for that template instead of just dumping text as it currently does.

I have put templates into emails/shareyourpaper/

There are five. Their file names match the current titles, but later I plan to make better subjects inside the emails. I have copy pasted the most recent copy in there for now until you hook up metadata and what not, just to keep everything a bit less confusing, and after you hook up and test I'll go in and mess around with copy.

**Comment by JosephMcArthur** [comment] 2020-01-23 08:05
> As far as I can see the JSON in the instantill emails is formatted in the same way. What difference is it you are wanting?

I just forwarded you an InstantILL email. Note that for the metadata we have clean headers, without "" and :{ etc. 

> For copy/pasting into spreadsheets, I guess you could dump data to a table in the email. It would need to be an html template for that, not a text template. Or else add the data as a csv attachment, but that is probably more hassle than just copying it out of the email.

We can ignore this for now giving we'll have spreadsheet export on day one and both can operate at the same time. 

> And for showing the fields we normally get even if there is no value, yes, if you listed them in an email template they would show up even if the value to go next to them (or under them if done as a table) ends up being empty.

That's great. Do you have a good place to look for all the fields we get so far, and info on how to list them in the file?

**Comment by JosephMcArthur** [comment] 2020-01-23 08:05
Oh, damn, I forgot, I added `successful deposit` for the email that would be generated when we get something right into zenodo. I don't think we currently have an email for that, or if we do I haven't seen it.

**Comment by JosephMcArthur** [comment] 2020-01-24 11:33
- [ ] can we stop mailgun sticking wrappers around all these emails?

e.g 

> http://email.mg.openaccessbutton.org/c/eJwVjjsOgzAQRE9jSuT1DyhcJCR0kXIFY6-BCDBazP1jpClmivc0wY4am8irxQouOAfQwKUAqKFun5JDp9591-pWwoMpvk11OnB33uN5jlfOaa8TTdVsvQ_BeYNRh1E40cmu0U7LCMIY06pYrXbO-WDywcRQghcV07H5my_bUV78imep30-vwDTGKCaHI0QmX4R7QKrI_hKWG7RMRZYIT3Tk51vxB9SaPZI

**Comment by JosephMcArthur** [comment] 2020-01-24 11:40
- [ ] can we make our sender name not `deposits@openaccessbutton.org` but `shareyourpaper.org`

**Comment by JosephMcArthur** [comment] 2020-01-24 14:05
Right, I have copy for [these emails sorted](https://docs.google.com/document/d/1EfeNReBYsnYyAcyvxS71rC97ovN4LY9NQ1DooCnocP4/edit#heading=h.a25ve0ulcf5d), but I haven't put it in the codebase yet (asking for feedback).

One note for you @markmacgillivray as you continue Zenodo deposit. I *think* the embargo email doesn't need to exist, I think we can just add an embargo statement line to other emails. So, we'd have emails for:

* successful deposits
* redeposits
* dark deposits
* forward deposits (deposits requiring manual review) 

What you currently have as the embargo email would be a great starting point for a successful deposit email. I think you can just rename and what not.

**Comment by JosephMcArthur** [comment] 2020-01-28 19:25
Okay, I think the main block here to me testing and trying these in action would be getting the codebase to read from the new templates! 

So, Mark, I think you're good to go on that. If you want a test with real copy, I think the dark deposit message in the link about should be easy to drop in and see if everything hooks up.

**Comment by JosephMcArthur** [comment] 2020-01-29 10:27
okay, all the emails are in the code. Once you attach them, most parts of them should work ( I likely got some field names wrong, and or they'll change, but none the less on the whole they should be okay.

**Comment by markmacgillivray** [comment] 2020-01-30 07:13
This is still to be done

**Comment by JosephMcArthur** [comment] 2020-02-03 23:34
Would you be able to double-check my understanding of the various emails we have now:

Zenodo deposit = the email sent when a deposit ends up in zenodo. This can include embargo info if there is embargo info.
Forward deposit = the file needs review and upload to the IR. This can include embargo info if there is embargo info.
Redeposit = deposit when it's already OA
Dark = deposit when permissions says nothing can be deposited
Review = Wildcard, goes only to us and catches when there is no-one else to send to and / or other weird issues

I've written the emails to align with the above so far, but can change!

**Comment by markmacgillivray** [comment] 2020-02-03 23:37
Yes that sounds fine. I can put those emails into the backend deposit code workflow.

**Comment by JosephMcArthur** [comment] 2020-02-03 23:39
Great! I think if you can make them read from the templates, I can fix individual fields from there. The one I'm not sure about is how to pass the checksum so that admin_confirms gets set. If you could tell me that here, I can slot that in too.

**Comment by markmacgillivray** [comment] 2020-02-03 23:42
It would go on the end of a deposit URL, so the email would need to include a link to the deposit page such as:

https://shareyourpaper.org/10.1234/567890?confirmed={{perms.file.checksum}}

**Comment by JosephMcArthur** [comment] 2020-02-03 23:47
can that always be `https://shareyourpaper.org`, or does it need to be their URL?

**Comment by markmacgillivray** [comment] 2020-02-03 23:51
It can be any URL you want as long as it is one that we know. If you want it to be the url where they embedded their shareyourpaper embed then it would be at {{embedded}}

**Comment by JosephMcArthur** [comment] 2020-02-04 00:08
I've got that in the file now. I think now the next thing is for you to get them hooked up and with the nicer formatting addition from InstantILL. 

For now, having them hooked up matters a lot more than having them look good, if you're squeezed for time.

**Comment by markmacgillivray** [comment] 2020-02-04 08:06
I have renamed the files to remove the whitespace and add underscore.

Also, in some places file. was directly referred to whereas it should be permissions.file. so I have changed those. In others there was deposit.X but deposit. is not needed because that is the tope level of the object being passed anyway. However there are still some in there that I do not know - for example, deposit.url has now become just url, but in either case, I don't know what value you want there. What URL? I don't think we store a URL for a deposit. We do have a zenodo URL later after deposit, but that is only relevant to the zenodo one, where I have added that.

Also most of the templates use reference to ricks.X but we don't have the ricks data directly at that point - we have the output of our permissions endpoint. Can you alter those to use the values that we have calculated rather than the ricks ones?

Also many of these use variable names that I think are soon to be changing, because you have asked for some of them to change. So just note, these will have to be updated to keep them working if we change any variable names.

I have uploaded the dev templates into the dev system, but I have not tried submitting a deposit to get it to trigger one of those emails.

**Comment by markmacgillivray** [comment] 2020-02-04 08:17
@JosephMcArthur reminder for you - if you update the email templates and want to see if your updates work, you need to push your changes to develop branch. Then go to the dev api and trigger a templates refresh so that the updated templates in the dev branch get loaded into the system. The endpoint at dev.api.cottagelabs.com/service/oab/templates shows all the currently loaded templates, and adding the param ?refresh=true will try to refresh them from the git repo.

**Comment by markmacgillivray** [comment] 2020-02-04 08:18
Oh I also removed a line from your templates - you had included a line linking to the API saying something like "go here for all the info about the deposit". But we have not made that endpoint, so it does not exist to link to. We could make it, but would need to create and schedule an issue for that.

**Comment by JosephMcArthur** [comment] 2020-02-04 13:07
Okay, so I need to tidy these emails up a lot, but I realized I have control over formatting (which was really obvious before, but I just didn't realize), so I think closing this is on me now.

To close, I need to:

- [ ] add headers I want in metadata sections
- [ ] fix ids I screwed up
- [ ] finish testing
- [ ] ask Q's about from the permissions info and deposit, but those can be separate issues.

**Comment by JosephMcArthur** [comment] 2020-02-04 13:09
Oh wait, there is one thing I need from you Mark. 

It looks like author names are coming out as 

> [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

You can see this in:

> Deposit Requires Checking: 10.1073/pnas.1905762116 1580812321455

We need that fixed.

**Comment by markmacgillivray** [comment] 2020-02-04 22:02
OK authors should come out as names now

**Comment by JosephMcArthur** [comment] 2020-02-08 10:45
A few things from testing:

- [ ] I'm still seeing issues with authors. The same as above
- [ ] When a field (e.g from ricks) is blank, I think currently the tag is just returned in the email. Instead, we should return nothing. You can see this with 10.1186/1758-2946-3-47. 
- [ ] how can we give oa urls in the emails? E.g if we do a redeposit we should be able to give them the open access url we found.

**Comment by markmacgillivray** [comment] 2020-02-10 18:15
If an OA URL was present for a redeposit, for simplicity I have put it in the url param, so all you will need is {{url}}. I have also changed that in the redeposit and review deposit templates, and altered the params you were using to try to get zenodo data.

**Comment by markmacgillivray** [comment] 2020-02-10 18:18
I've tested those and it works now. I will assign to you in case you want to make any other template / param changes, otherwise you can close if happy.

**Closed** 2020-02-10 18:31 UTC
Labels: 2. Enhancement
