### ISSUE TITLE
Displaying integration URL on InstantILL set up displaying false

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1355] opened 2020-01-03 12:43 UTC
I have an embed on dev with uid: JkXSRq7RffwjgHQEn that I have used on here: https://josephmcarthur.github.io/playground/instantill_test.html. 

That URL should come up below, but it doesn't, instead i see `false`. 

![image](https://user-images.githubusercontent.com/4953703/71723933-57821800-2e26-11ea-8619-b4c3f0cfb285.png)

I recently changed this code, so may have introduced an error.

As a reminder, it's indended to show the URL a uni has embeded the plugin on. If they haven't embeded / used it elsewhere, and have only used it on the oab or instantill site, then it should show instructions for set up.

**Comment by markmacgillivray** [comment] 2020-01-06 22:34
OK I think I have this fixed now, it was likely caused by our change to the new find API, as it returned this data back slightly differently. Can you please have a look at your setup page again and see if you see the right URL there now, if so close it. Once this bug is confirmed fixed I will do the push to live as that will be all the main things for the demos to be working properly, then I will go back to milestone 74 UI developments.

**Closed** 2020-01-07 13:40 UTC
Labels: 1. InstantILL, 2. bug
