### ISSUE TITLE
Button sending users to a non-OA IR link for DOI 10.1179/030801802225002881 

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#560] opened 2017-02-23 16:50 UTC
I searched for DOI 10.1179/030801802225002881 and the Button told me it was available at http://nora.nerc.ac.uk/13191/. However, this item in the repository is not Open Access and requires a login to view. Since the article was published in 2013 I do not believe this is just an embargo.

**Comment by markmacgillivray** [comment] 2017-02-23 18:52
We do have a lot of the problem of items requiring a login to view - but that is not the same as not open access. Do you know it is not available without login AND that it is also not open access? It is in a repo called the NERC open research archive, and it is an eprints archive, and it does not say that it is closed, as far as I can see - it just says you have to login / request a copy.

Please clarify if there is something more specific about this one making it not open access.

If it is just the problem of login - yes, that is a problem, but one we already know about and have an issue open for already, I think. And it is hard to solve, short of crawling everything ourselves, which we have also discussed.

**Comment by chealsye** [comment] 2017-02-23 19:02
The full text is not available in the repository and it requires staff login. That is not Open Access. This particular item in this repository meets no standard definition of Open Access. We should not be sending users to this repository for this item.

If I was a first time user and searched for this article with the Button (and I did so because it was mentioned in a FiveThirtyEight piece) and couldn't get access but was told by the app there was access I probably wouldn't use the Button again.

**Comment by markmacgillivray** [comment] 2017-02-23 19:19
OK, so this is the same problem we have seen before.

The item does meet the definition of open access used by the aggregators we use - therein lies the problem. Something is considered open access if it is in a repo and is said to be open access, EVEN IF login is required to access it.

We will be returning quite a few results like this, and there is very little we can do about it, short of crawling all repos ourselves.

I do agree with you that it is not great for a user, and I would not find it good enough - it's just not actually a new problem.

**Comment by chealsye** [comment] 2017-02-23 19:28
I'm aware this is a problem that has already been reported. I'm reporting this specific instance so we can correct it.

I understand why a system would think it is Open Access. This will happen for metadata only records or embargoed research output, but we can still improve the individual problem. 

We can't crawl repositories ourselves to find all these little issues, but when an individual problem gets report either from a team member or a user the link can be removed and then a request created for the article. I don't have the ability to remove that link, so I'm reporting it as a bug.

**Comment by markmacgillivray** [comment] 2017-02-23 19:35
At the moment we don't have a way to override what one of our sources claims as open access - we can't yet blacklist things that we find.

To give you more background, the article you refer to was found by us in BASE, and their raw record can be seen at:

https://dev.api.cottagelabs.com/use/base/doi/10.1179/030801802225002881

There is no way from that article to identify it as open or not, other than the fact that it is there in BASE.

As you say, many records will be metadata-only, and not accessible via login.

We could introduce a blacklist of discovered URLs, and you could then start adding URLs to the blacklist, but it is likely we will end up with a very large blacklist - it is common to find records like this in BASE and in other sources.

We can actually crawl repositories ourselves, if we decide to take that approach.

Or we can introduce blacklisting of apparently open sources.

Other than doing one of those, I don't think we can improve on these individual cases.

Because we know the problem exists, and this is within expected behaviour, it becomes a feature request rather than a bug. Now we have to decide if we want to put the time into implementing this feature, one way or the other (or come up with a different solution).

**Comment by markmacgillivray** [comment] 2017-02-23 19:38
When you see problems like this case, or when people report them to you, would you be able to work out if the entire site not open? i.e. for this one, can you tell that nothing on that nora.nerc.ac.uk domain can be accessed without a login? And if so, would you want to be able to say that means it is not open, even if many other sources claim that it is?

If so, given that we already have a blacklist google spreadsheet, I could add a check of that spreadsheet to every result URL we can find, and if it appears to be a URL on a domain on that blacklist, we can ignore it.

That is probably the fastest and simplest solution - then on a case by case basis, as issues are discovered, you could do something about it.

**Comment by markmacgillivray** [comment] 2017-02-23 19:52
@chealsye @JosephMcArthur I have implemented the aforementioned proposed solution on the dev api - it will not return a url as open if part of the domain is in the url blacklist google spreadsheet. I can easily disable or enable this, so if you decide this is an approach you want to take, just let me know and it can go live, and you can then add the domain names of sites you don't want to include as open into the blacklist google sheet.

**Comment by chealsye** [comment] 2017-02-23 19:55
I'm not saying anything about blacklisting. This is one item. We know it isn't accessible yet we'll continue referring people. I don't know why it isn't possible to tell a system to not include a certain full url or that DOI XXX or Title Y isn't available, or to add a different url when it is found. A user (even a team member) is incapable of starting a request in this instance. The Button is not working how we tell people it works.

This isn't a feature request. We're incorrectly telling someone it is available. We don't allow them to create a request even if we can confirm it isn't available. The Button does not do its job in these cases. I see that as a bug and a problem. We can't prevent it for all embargoes papers, metadata only records, and odd instances of institution-only access. We can't 'blacklist' repositories. But when it is caught we should have a method for helping. We should be able to remove inaccurate links and start requests.

**Comment by markmacgillivray** [comment] 2017-02-23 19:55
So for example the discovered URL in this case could be blocked by adding nora.nerc.ac.uk to the blacklist sheet, and then we would never return anything from that site as open. OR, to just block the one case of this URL, nora.nerc.ac.uk/13191 could be added to the blacklist (but note if we do this on an individual url basis, it could get looooooooong....)

**Comment by markmacgillivray** [comment] 2017-02-23 20:01
@chealsye does my last comment explain how you could do this at a repo or individual article level?

It isn't a bug. It is doing what we expect. Whether or not it is doing what we tell people it is doing depends on your definition of open. Right now, the way we return things keeps us in line with what the major aggregators we use also claim as open. If we deviate from that, we are making a specific decision to be different from those results, and a specific decision to implement that in our code. It is not a fix, it is a choice.

Either way, whatever terminology we use for it, I have proposed and implemented a solution on dev. This solution will allow us to catch when we have told someone the wrong thing, then mark it as wrong, then tell them they can try again, and then they could make a request. Let me know if that is acceptable.

There is no way we can do this in advance - someone will have to find the problem, report that they expect access, and then we could blacklist. The only way to do it in advance, given what I've explained about the sources we use, is to do our own crawling.

**Comment by chealsye** [comment] 2017-02-23 20:12
Blacklisting whole repositories is not a solution to an individual item that requires a login (or is embargoed or is metadata-only).

I don't care if it is "looooooooong" - if the url is not correct that should removed.

It is doing what *you* expect, not what users expect. We tell people the Button connects them to open research and we request research not yet available. The Button is doing neither in this case and the other instances where the Button is inaccurately telling users research is available. So, sure we can change the language - I think we should make a *choice* to do what we say we do when we are told it isn't working. 

I'm quite aware of the limitations of knowing these problems before they are discovered. As I have already said when an individual problem gets reported either from a team member or a user the link can be removed and then a request created for the article.

**Comment by markmacgillivray** [comment] 2017-02-23 20:14
OK, so what I'm saying is that if you are happy to add individual URLs to that blacklist google spreadsheet, then they will not be served to a user as open on subsequent retries. If you also happen to find entire repositories that are not open, you can add the domain name too, and save yourself the hassle of adding individual URLs, and potentially saving users getting "non-open" links in the first place.

Does this sound solved? Or is there something else I'm missing?

**Comment by markmacgillivray** [comment] 2017-02-23 20:16
Also, no, it is not what I expect - it is the consensus of the aggregators in the area we are working in.

What I expect is to get access without login - that is why I would propose doing our own crawling.

**Comment by markmacgillivray** [comment] 2017-02-24 13:29
@chealsye thanks for logging issues, this has generated good discussion. I have talked to @JosephMcArthur and proposed an addition to this solution. It provides a way to collect the data we would need for crawling, and enables us to be more specific about when we do or do not send someone to a page that could or could not be accessible. It needs a few steps, but should be quite simple. Let me know what you think, and we can implement this quickly. I'll use nerc as the example.

0. We start a new google sheet called fulltexts (or whatever) with the columns DOMAIN, SUFFIX, ELEMENT

1. Someone finds a site that has some articles available without login, but some that need login (like nerc)

2. Look at an article page on that site for one that IS available without login, and find the URL to the full article

3. Look at another accessible article page on that site, and see if the full article URL has a similar pattern - this is not the case on nerc, but for example on HAL, you would see the page URL is:

https://hal.archives-ouvertes.fr/hal-01379720/document&sa=D&sntz=1&usg=AFQjCNFantzjXp8Wnh2eQQy3Df1qyXiL1A

and the full article URL is the same but with /document stuck on the end - and this can be verified by looking at a couple of HAL pages. Where such a pattern exists, go to the google sheet and put in the HAL domain in the DOMAIN column ( https://hal.archives-ouvertes.fr ) and /document in the SUFFIX column - done!

4. In the case where the above is NOT true, such as on nerc where they do not have an easy pattern to the full article pages, but where we know SOME items are available without login, find an article that IS available without login. On that page, click the link that opens the full article, then copy the full article URL once it opens. Then, on the page where the link was found, right click and select "view source". Once the source page opens, search it (using ctrl-f) for the full article URL you just copied. When an element is found on the page with that URL as the value, note the name of the element.

For example, on nerc, there is an article that IS available at http://nora.nerc.ac.uk/514905. On that page, unlike the one you found at the start of this issue, there is a fulltext download link, and when opening it we can copy the URL http://nora.nerc.ac.uk/514905/1/Arivalagan.pdf. Then back on the article overview page we can right click, view source, and search for the pdf URL, and we find:

&lt;meta name="eprints.document_url" content="http://nora.nerc.ac.uk/514905/1/Arivalagan.pdf" /&gt;

So now, we can go to the google sheet and enter http://nora.nerc.ac.uk in the DOMAIN column, leave the SUFFIX column blank, and in the ELEMENT column, copy the element UP TO the URL value:

&lt;meta name="eprints.document_url" content="

and done!

5. An extra step - you could also still choose to blacklist a specific URL in cases where we know it is not available, or blacklist an entire site where we know it mostly requires login. So for nerc, let's say you provide the above info in the new google sheet, and then also add "http://nora.nerc.ac.uk" in the blacklist google sheet we already have, we would know that IF we find a fulltext URL then we can send the user there, but if we don't then we should NOT send the user there. Alternatively, you may find other websites that are almost always open, so we may be happy to still send people there even if we can't find a fulltext url, as the chances of us being wrong are much smaller - so in these cases, we would not add the domain to the blacklist sheet.


----------------------------------------

The above five steps would give us quite fine control over what we send people to, and if in future we do decide to do our own crawling this is also the information we would need, so it makes us more robust to any future issues with the sources we currently query.

Also, of course, whilst this example is based on you finding nerc, it is not just you that would have to do this - as with the blacklist google sheet, anyone on our team (or beyond, if we desire) can be given access to the sheet and keep it up to date.

There would still be occasional initial cases where we may send someone to a page that requires login and they complain, but now we have a way to fix that. Also, we can pre-empt that for any major repos we can think of by having someone populate the new google sheet with the necessary info in advance.

Let me know what you think, and if good I can add this to dev pretty quickly.

**Comment by JosephMcArthur** [comment] 2017-02-24 13:40
Just to be clear, even in places where we don't have this "login" issue, we can use this to increase full text link-through, closing #461. This could be a significant increase in our usability for quite a low cost.

**Comment by chealsye** [comment] 2017-02-25 22:19
@JosephMcArthur What am I being assigned to do?

**Comment by JosephMcArthur** [comment] 2017-02-26 10:36
Your thoughts on the above would be great! Sorry, I guess that isn't clear.

**Comment by svmelton** [comment] 2017-02-26 23:57
Just a note that this is similar to what I documented in #241.

**Comment by JosephMcArthur** [comment] 2017-02-28 14:53
So, when we get this implemented it would also be good to track how many things are in each repo. Then we could start a running twitter thing of "xxx more full text links in the button today", and "xxxx login pages avoided" etc. I think that would be easy and fun to do!

**Comment by markmacgillivray** [comment] 2017-02-28 16:31
The availability checks record where they found something, but it is a record of the source that told us where it was - e.g. the source would be BASE, not an institutional repo. BUT we can infer the final sources from the domain names they are on, and that could already be queried from the data. It could be added to the stats page.

We have also previously talked about the API automatically tweeting things, but it has not made progress. The functionality is there, and I could have it tweet certain numbers, I just need to know what you want it to say and when.

Also, the API can respond to tweets too - if someone tweeted at oabutton #find SOMETHING then we could respond with a link or a request page. Again, just need to know what you want it to monitor to respond to, and what you want it to say in return.

**Comment by JosephMcArthur** [comment] 2017-02-28 19:53
Moved your tweeting comments to #574. 

In terms of the system described, how would we handle Citeseer? We often send people but only link to the splash page. The fix is:

Splash: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.221.2601
Fulltext: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.221.2601&rep=rep1&type=pdf

Here the change is in the middle of the URL & end.

**Comment by markmacgillivray** [comment] 2017-02-28 20:23
For these we would need two more columns - "REPLACE" and "WITH", before "SUFFIX". In "REPLACE" you put in the part that needs replaced, and in "WITH" you put in what to replace with. In this case it would be "summary" and "download" - and you'd still need to put "&rep=rep1&type=pdf" into "SUFFIX".

**Comment by markmacgillivray** [comment] 2017-02-28 20:26
An alternative, possibly simpler depending how you think about it, would be to use two columns called "SPLASH" and "FULLTEXT" and in those columns you put example splash and fulltext URLs for the same article. From this I could probably discern the differences of other URLs we saw like that.

Anyway, the exact details of what goes in the spreadsheet are less important than just agreeing that people are happy to do this approach, and that somebody somewhere would put things in the spreadsheet. If that is the case, I can quickly make one and hook it up to the code and decide the best approach for putting the info in the sheet.

**Comment by JosephMcArthur** [comment] 2017-02-28 20:31
I can't see a downside to this:

* we can stop people going to urls we know are bad for specific articles
* we can link to full text way more often
* where repo's often contain login walls (or other things which block users) we can get better at detecting this & make case by case decisions on if we still want to use them. 
* we can stop us getting researchgate from places like dissem.in when they turn that on

Lets get a sheet ready. I'm talking to @meganwaps about filling the sheet tonight after our team call.

**Comment by markmacgillivray** [comment] 2017-02-28 20:49
It could work for dissemin, but as dissemin is just a case of one URL, I have already added a filter on it for researchgate anyway.

**Comment by JosephMcArthur** [comment] 2017-02-28 22:40
Note to @meganwaps, where to start:
* availabilities spreadsheet (as discussed)
* Looking at our sources's biggest contributors (e.g who contributes the most articles to base etc
* issues flagging this problem

 - [ ] @markmacgillivray can we have a spreadsheet to start this that aligns with what you need. 

We also need a way in that sheet, or a sheet, to record URL's we've tried to look at, but failed to find a way to get to full text / avoid login-walls.

**Comment by markmacgillivray** [comment] 2017-02-28 22:49
@JosephMcArthur can you create the sheet, that way you can put it into whatever folder you all usually use to share access across the team, then give me the link. From that I can set the API to read it, and will put in the column names we can try.

For recording that you looked at a URL but could not find a way round, just put the URL in the sheet but don't fill in any of the other fields - then later if we do find a way round, they can be added. (And when adding new URLs, search first in case it is already in there.)

**Comment by JosephMcArthur** [comment] 2017-02-28 22:54
So... this is the URL: https://docs.google.com/spreadsheets/d/1Te9zcQtBLq2Vx81JUE9R42fjptFGXY6jybXBCt85dcs/edit#gid=0

Can you build the sheet as you need it? Just not clear which version of the above you plan to use.

**Comment by markmacgillivray** [comment] 2017-02-28 23:20
OK I have added some column headers and put notes on them, it is not quite the same process as above, but should be pretty obvious. Try it and see - if it does not work out we can make tweaks later. Stick the nerc example in there, the one above that kicked off this issue, and once you have I will hook it to the API and we can see that the API should no longer direct us to that URL that requires a login.

**Comment by JosephMcArthur** [comment] 2017-03-01 08:41
Okay, assigning @meganwaps to take this forwards

**Comment by JosephMcArthur** [comment] 2017-03-30 19:22
@markmacgillivray I've started to put repo's in here, is it hooked up?

**Comment by markmacgillivray** [comment] 2017-03-30 21:00
No it isn't. As above, once you're happy with the layout of the sheet I can try hooking it up. However at the moment the sheet has URLs in columns I would not expect them in, so I don't know how to make use of it yet.

**Comment by JosephMcArthur** [comment] 2017-03-30 21:11
Where wouldn't you expect URL's? I thought we were using it okay!

**Comment by markmacgillivray** [comment] 2017-03-30 21:23
The column called BLACKLIST has URLs in it, but should just contain "yes" or be empty. The URLs that are in there appear to be specific URLs that are wished to be blacklisted - not entire repositories, which was the use case we discussed. If you want to blacklist specific URLs but not the domains they are on (for example a few in that list are PMC articles, not clear why they'd be blacklisted) then that requires a different approach.

**Comment by JosephMcArthur** [comment] 2017-03-30 21:36
okay, cleaned that up and made a sheet for specific domains:
https://docs.google.com/spreadsheets/d/1f3dyU0xmCh2fgEMgNY1yHSXqyB0j6WZ_WDeS2AS669M/edit#gid=0
.

On Thu, 30 Mar 2017 at 22:23 markmacgillivray <notifications@github.com>
wrote:

The column called BLACKLIST has URLs in it, but should just contain "yes"
or be empty. The URLs that are in there appear to be specific URLs that are
wished to be blacklisted - not entire repositories, which was the use case
we discussed. If you want to blacklist specific URLs but not the domains
they are on (for example a few in that list are PMC articles, not clear why
they'd be blacklisted) then that requires a different approach.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/OAButton/discussion/issues/560#issuecomment-290549060>,
or mute the thread

**Comment by markmacgillivray** [comment] 2017-03-31 12:05
We already have a sheet for blacklisting specific URLs. So far it has been used for blacklisting sites we don't want people to use the button on, like facebook. But you can just put any URL in there and it will be blacklisted from results too.

Note that the blacklisting is flexible - the shorter a URL you put in the blacklist, the more it will block. So facebook.com blocks all of facebook, but facebook.com/MYUSERNAME only blocks things under MYUSERNAME part of the facebook site.

There's not much point having two separate sheets of blacklists.

The newest sheet was supposed to be for sites where we want a way to check if there is a fulltext link - that was the difference it was created for, over and above the sheet we already have.

**Comment by JosephMcArthur** [comment] 2017-03-31 12:36
Ah, okay! I didn't realise we could just use that sheet for this too. Have added the URL's to that sheet.

**Comment by JosephMcArthur** [comment] 2017-04-02 20:34
Okay, to update here. I've now done 20-ish repos, including some huge ones (e.g arvix / citeseerx / hal). Some patterns are emerging:
* there are only a few types of meta-tags normally used
* these meta-tags often lead to a login wall even if they say they go to a pdf. This means you then need to grab the URL of that page & put that on the blacklist. 
* if someone uses the frontpage on the same paper twice quickly it's often a good sign of an error (perhaps a suggestion we can auto-flag). 

I've also got a sheet going where I have lots of notes / data on this: https://docs.google.com/spreadsheets/d/1sEBqx7GPyCKiktzLWhQ4tlwPcuTZvdSH0rCFP5LQs_4/edit#gid=1125772957

**Comment by JosephMcArthur** [comment] 2017-04-07 12:21
Note to self: A list of  https://www.base-search.net/about/en/about_sources_date.php?menu=2&submenu=1. Checked openaire, core & share but they didn't have lists 1/2 as helpful as this.

**Comment by JosephMcArthur** [comment] 2017-04-07 13:58
Also, @markmacgillivray often we link out to domains like "http://hdl.handle.net" rather than actual repo urls (like https://repository.si.edu/handle/10088/12131 ). Will that affect they system, and should I be storing this URL?

**Comment by markmacgillivray** [comment] 2017-04-07 14:07
We don't currently resolve handle URLs at all, so that means we do not know what is at the end of them. If we are to automatically check that what is at the end of them is open, then yes we will need information about the terminating address, not the handle address. And we will need to start resolving all handle URLs.

**Comment by JosephMcArthur** [comment] 2017-08-02 11:15
to close this we want to:

- [ ] resolve handle / doi's to their URL's
- [ ] have the redirect sheet working

**Comment by JosephMcArthur** [comment] 2017-08-27 11:54
For the record, Mark & I spent about half a day planning this fully (it's complex af) this week.

**Comment by markmacgillivray** [comment] 2017-12-25 12:08
Testing on my local system this works now - the DOI of this example is considered inaccessible. Once I update dev with this, will assign to joe to test.

**Comment by markmacgillivray** [comment] 2018-01-04 06:32
Dev is up to date now.

**Closed** 2018-04-10 13:56 UTC
Labels: 1. API, 2. bug, 3. Blocked: Dev, 3. Blocked: Test, 4. Priority, 4. bug: FT RD (temp)
