### ISSUE TITLE
Supporting use for more repositories 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#1681] opened 2020-09-28 13:31 UTC
Support all repositories by adding subject repository permissions. If required, add support for named repositories. This is in order to streamline messaging, support use by more repositories (e.g OSF pre-print repos), and better comply with publisher policies.

More planning in this document: https://docs.google.com/document/d/1EJwQA65xiL9Z27O3cAlYjdn_tATpwCbgb5ZzJA4upRY/edit#

TODO

We currently only have data for institutional repository permissions. In order to understand the current state of other types of repositories, review all publisher permissions and identify permissions information for other repositories.

- [ ] Identify the different  types of repositories mentioned 

- [ ] Record specific repository names mentioned by publishers in their policies and see in which cases we want to include them in the database. 

- [ ] Add new records for publishers where policies for different types of repositories differ from each other. 

- [ ] Add additional publisher webpages where hosting policies are mentioned to perma and wachete

-  The system should ideally give out a final answer and not making users have to go through extra steps to find out where they can deposit
1.  How would we tell authors exactly which repositoires are mandated by their funder? 
2. How can we make the repositories we point to easy to access, eg.  guide authors directly into depositing to PubMed 
3. Evaluate: https://transpose-publishing.github.io/#/ . See if its worth adding info about preprints

**Comment by JosephMcArthur** [comment] 2020-11-09 08:21
duplicate of #1681

**Closed by JosephMcArthur** 2020-11-09 08:21 UTC
Labels: 2. enhancement
