### ISSUE TITLE
Email: "Review Deposit {{metadata.doi"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1619] opened 2020-06-08 18:34 UTC
No idea what happened with this deposit. The DOI has researchgate in the title, is this our blocking system mis-firing by any chance?

**Comment by markmacgillivray** [comment] 2020-06-22 22:09
This was likely caused by missing metadata, and that meant the template could not fill in properly. This issue should not exist any more because I already changed how that handles when info is missing, whilst working on refactor stuff. So I will close this one, we can re-open if it comes up again.

**Closed by markmacgillivray** 2020-06-22 22:09 UTC
Labels: 1. shareyourpaper.org, 2. fix
